#!/bin/bash
set -e

ROOT_PWD=$( cd "$( dirname $0 )" && cd -P "$( dirname "$SOURCE" )" && pwd )

# 构建目录
BUILD_DIR=${ROOT_PWD}/build
if [ -d "${BUILD_DIR}" ]; then
  rm -rf ${BUILD_DIR}
  echo -e "\033[1;31mDeleting existing build directory: ${BUILD_DIR}\033[0m"
fi
mkdir -p ${BUILD_DIR}

cd ${BUILD_DIR}

cmake -DCMAKE_TOOLCHAIN_FILE=/home/mc/toolchain-rockchip-aarch64.cmake \
-DCMAKE_BUILD_TYPE=RELEASE \
-D WITH_LIBV4L=ON \
-D WITH_V4L=ON \
-D WITH_GSTREAMER=ON \
-DBUILD_SHARED_LIBS=ON \
-DCMAKE_CXX_FLAGS=-fPIC \
-DCMAKE_C_FLAGS=-fPIC \
-DCMAKE_EXE_LINKER_FLAGS=-lpthread \
-DBUILD_TESTS=OFF \
-DBUILD_PNG=ON \
-DBUILD_JPEG=ON \
-DBUILD_ZLIB=ON \
-DBUILD_FFMPEG=ON \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_opencv_apps=OFF \
-DENABLE_PIC=ON \
-DWITH_1394=OFF \
-DWITH_ARAVIS=OFF \
-DWITH_ARITH_DEC=ON \
-DWITH_ARITH_ENC=ON \
-DWITH_CLP=OFF \
-DWITH_CUBLAS=OFF \
-DWITH_CUDA=OFF \
-DWITH_CUFFT=OFF \
-DWITH_FFMPEG=ON \
-DWITH_GSTREAMER=ON \
-DWITH_GSTREAMER_0_10=OFF \
-DWITH_HALIDE=OFF \
-DWITH_HPX=OFF \
-DWITH_IMGCODEC_HDR=ON \
-DWITH_IMGCODEC_PXM=ON \
-DWITH_IMGCODEC_SUNRASTER=ON \
-DWITH_INF_ENGINE=OFF \
-DWITH_IPP=OFF \
-DWITH_ITT=OFF \
-DWITH_JASPER=ON \
-DWITH_JPEG=ON \
-DWITH_LAPACK=ON \
-DWITH_LIBREALSENSE=OFF \
-DWITH_NVCUVID=OFF \
-DWITH_OPENCL=OFF \
-DWITH_OPENCLAMDBLAS=OFF \
-DWITH_OPENCLAMDFFT=OFF \
-DWITH_OPENCL_SVM=OFF \
-DWITH_OPENEXR=OFF \
-DWITH_OPENGL=OFF \
-DWITH_OPENMP=OFF \
-DWITH_OPENNNI=OFF \
-DWITH_OPENNNI2=OFF \
-DWITH_OPENVX=OFF \
-DWITH_PNG=OFF \
-DWITH_PROTOBUF=OFF \
-DWITH_PTHREADS_PF=ON \
-DWITH_PVAPI=OFF \
-DWITH_QT=OFF \
-DWITH_QUIRC=OFF  \
-DWITH_TBB=OFF \
-DWITH_TIFF=OFF \
-DWITH_VULKAN=OFF \
-DWITH_WEBP=ON \
-DWITH_XIMEA=OFF \
-DBUILD_opencv_xobjdetec=OFF \
-DBUILD_opencv_world=ON \
-DBUILD_LIST=core,highgui,videoio,imgcodecs,imgproc,video \
-DCMAKE_INSTALL_PREFIX=../install ..

make -j${nproc}
make install
cd -